name: oatpp-prebuilt-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    env:
      mingwTargetZip: oatpp-${{ github.ref_name }}-mingw.zip
    steps:
      - name: git clone oatpp
        run: git clone --branch 1.3.0 https://github.com/oatpp/oatpp.git

      - name: cmake oatpp
        shell: cmd
        run: cd oatpp && cmake.exe -G"MinGW Makefiles" -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX="build/oatpp" -B./build
      
      - name: mingw build 
        shell: cmd
        run: cd oatpp\build && mingw32-make install
        
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: "zip"
          directory: "oatpp/build/oatpp"
          filename: "${{ env.mingwTargetZip }}"
          
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "oatpp/build/oatpp/${{ env.mingwTargetZip }}"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
